### ISSUE TITLE
已提交当前网站文件用于测试

### ISSUE THREAD

**Issue by ghost** [ustclug/ustclife#1]
请在搭建好服务后回复IP，我把解析CNAME过去试一下。

**Comment by zzh1996** [comment]
IP应该是A记录而不是CNAME

**Comment by ghost** [comment]
更正，我原意是回复域名，这样对LUG应该方便一些吧，一个机器上可以搭多个网站，用Host区分。不过如果能独占一个IP当然更好，那样就是A记录。

**Comment by gaoyifan** [comment]
服务已建好，请添加记录：

```
@   CNAME  cname.vm.ustclug.org.
```
