### ISSUE TITLE
增加本科生成绩单委托打印系统的入口

### ISSUE THREAD

**Issue by zhaohongzhu** [ustclug/ustclife#19]
地址为 http://verify-transcript.cmet.ustc.edu.cn/index.jsp
委托打印对不在校的同学申请出国 / 办理签证等很有帮助，然而这个网站目前四处都很难搜到。

**Comment by zzh1996** [comment]
@Smart-Hypercube 你在 URL 末尾多加了一个「/」，导致网页打不开

**Comment by SmartHypercube** [comment]
是 9eb927e6149cd2ba6abdd065665ffe20c85d44db 引入的问题，我昨天看到 404 ，还以为是没对校外开放而已，就没在意，只升级到了 HTTPS 。
