### ISSUE TITLE
把支持 https 的网站链接都改成 https

### ISSUE THREAD

**Issue by zzh1996** [ustclug/ustclife#23]

**Comment by doodlewind** [comment]
用 `<a href="//example.com">` 的格式是否更方便一些

**Comment by zzh1996** [comment]
这显然不对啊，这会导致用户访问网站时 http 还是 https 由用户访问 ustc.life 时的状态决定。如果用户访问了 https 的 ustc.life，那么那些不支持 https 的网站就会点不开
