### ISSUE TITLE
记录用户使用情况用于分析

### ISSUE THREAD

**Issue by SmartHypercube** [ustclug/ustclife#25]
可以从记录各链接的点击历史开始

**Comment by SmartHypercube** [comment]
怎样实现可以对用户访问体验，尤其是跳转速度产生尽可能小的影响呢？求大家建议

**Comment by doodlewind** [comment]
我们的线上产品使用了神策和 GrowingIO，它们都提供了无需代码埋点的 SDK 接入，但费用方面并不清楚，供参考哈。

https://www.growingio.com/
https://www.sensorsdata.cn/

**Comment by SmartHypercube** [comment]
可以使用 hyperlink auditing 功能来做

**Comment by JiangGua** [comment]
> 可以使用 hyperlink auditing 功能来做

受此启发，我简单写了一个处理 Hyperlink Auditing 请求的后端：https://github.com/JiangGua/pong
因为新打开的链接（href）是在新标签页打开，所以即便访问 Pong 后端速度较慢用户感知也不强。
