### ISSUE TITLE
更改自助复印打印网站

### ISSUE THREAD

**Issue by GongSiqiu** [ustclug/ustclife#29]
需要更换为
202.141.162.24:7480/xabprint

**Comment by SmartHypercube** [comment]
目前链接的似乎也仍然可以继续使用？有什么信息能证明这个比目前的链接好的吗？

**Comment by GongSiqiu** [comment]
目前的链接我和几个同学都打不开……

**Comment by SmartHypercube** [comment]
请张老师 @bg6cq 看一下，目前的链接是 http://202.141.162.24/XabPrint/Login.aspx ，我通过 LUG VPN 能打开，但不知道校内访问情况如何。这个是被封了吗？

**Comment by GongSiqiu** [comment]
校内IP可以打开，校外就不可以

**Comment by SmartHypercube** [comment]
确实是这样，最近有一些地址在校外被封了，我先改成这个能用的。感谢提醒。
