### ISSUE TITLE
可以考虑加入学在科大APP下载链接

### ISSUE THREAD

**Issue by linzihan322** [ustclug/ustclife#31]
学在科大APP集成了常用的链接，同时还加入了课程表、制定计划、立Flag、电子资源共享、大物实验数据处理、化学计算、专业介绍等特色功能

下载链接是：
http://home.ustc.edu.cn/~linzihan322/XZKD.apk

附部分页面截图：
![Screenshot_20190528_181253_com linzihan xzkd](https://user-images.githubusercontent.com/49679968/60715791-758ebe80-9f50-11e9-9a00-13f3412e3747.jpg)
![Screenshot_20190705_181429_com linzihan xzkd](https://user-images.githubusercontent.com/49679968/60716001-e930cb80-9f50-11e9-91e2-70a0969cee23.jpg)

![Screenshot_20190326_191929_com linzihan xzkd debu](https://user-images.githubusercontent.com/49679968/60715793-76275500-9f50-11e9-803b-e4104db67636.jpg)

**Comment by SmartHypercube** [comment]
抱歉，app 下载链接不属于常用网站，不符合本项目制作科大导航首页的目标，我认为不应该收录。

**Comment by zzh1996** [comment]
@linzihan322 你可以把这个 app 加入 https://github.com/zzh1996/USTC-Network-Resources ，欢迎提 pull request
