### ISSUE TITLE
添加校园百科网址

### ISSUE THREAD

**Issue by liginity** [ustclug/ustclife#33]
https://wiki.ustc.edu.cn/

**Comment by cuihaoleo** [comment]
看起来还有个域名 https://baike.ustc.edu.cn/

**Comment by SmartHypercube** [comment]
网页源代码中出现的域名都是 baike.ustc.edu.cn ，应该采纳这个。

**Comment by zzh1996** [comment]
这是一个会被经常用到的网站吗？

**Comment by SmartHypercube** [comment]
我觉得并不需要“经常被用到”，现在就有一些网站是不常用的，但起到了一个“告诉大家还有这个网站”的作用。或许可以改版一下，把这类东西放在一个新栏目里，甚至可以每次打开时随机推荐一个“你知道吗”，这样
