### ISSUE TITLE
更换大物实验网址

### ISSUE THREAD

**Issue by Adven00** [ustclug/ustclife#35]
http://etis.ustc.edu.cn

**Comment by SmartHypercube** [comment]
请问旧的网址是不再使用了还是仍在使用？新网址是谁从什么渠道公布的呢？

**Comment by Adven00** [comment]
旧网址仍然是物理实验教学中心的官网，但其大物实验教学平台的功能（查询实验安排，下载讲义等）转移到了新网址，目前已经启用，只能用校园网登陆。
新网址目前尚不完善，将来应该会用于管理各种类型的实验。










发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hypercube <notifications@github.com&gt;
发送时间: 2019年9月18日 13:13
收件人: Smart-Hypercube/ustclife <ustclife@noreply.github.com&gt;
抄送: ustc-bhy <852536571@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Smart-Hypercube/ustclife] 更换大物实验网址 (#35)




请问旧的网址是不再使用了还是仍在使用？新网址是谁从什么渠道公布的呢？
