### ISSUE TITLE
体测成绩查询入口变更

### ISSUE THREAD

**Issue by hooooinwiki** [ustclug/ustclife#37]
本学期体测成绩查询入口由原有的
https://ty.ustc.edu.cn
变更为了
http://222.195.70.60/hi/view/mobile/login.html
参见：http://www.tj.ustc.edu.cn/2019/1009/c1452a393267/page.htm

**Comment by SmartHypercube** [comment]
经过测试，似乎是原来的 /view/... 坏了，现在在 /hi/view/... 搞了一套新系统，其中 URL 结构和以前相似。所以我改成了我认为更合适的 https://ty.ustc.edu.cn/hi/ ，如果有问题欢迎重开本 issue。

**Comment by SmartHypercube** [comment]
改成了 https://ty.ustc.edu.cn/hi/view/mobile/login.html ，因为不加 mobile 的话会奇怪地显示教师登录的界面
