### ISSUE TITLE
添加bb系统和助教管理系统

### ISSUE THREAD

**Issue by TheLitFire** [ustclug/ustclife#42]
鉴于在疫情期间大量的访问需求，建议添加我校blackboard系统：
https://www.bb.ustc.edu.cn/
建议同时添加到“常用网址”和“学在科大”。

另外，我觉得助教管理也可以加入进来：
https://tam.cmet.ustc.edu.cn/
建议加入“学在科大”或“其他”

**Comment by SmartHypercube** [comment]
谢谢建议！
bb系统之前就有，在“学在科大 - 网络教学平台”，已同时加入“新冠疫情”分区。
助教管理已加入“学在科大”分区。
