### ISSUE TITLE
修改一下【常用网址】的收录

### ISSUE THREAD

**Issue by TheLitFire** [ustclug/ustclife#43]
根据本人三年来的使用情况，以及对于身边的很多人而言，【常用网址】部分不如：
- 把 “成绩单打印” 换成 “自助打印复印”

另，“瀚海星云” 还有人用嘛（

要不我们把 “网络教学平台” 加进常用吧（

**Comment by SmartHypercube** [comment]
我一直想改善一下“常用”这个分类，比如通过遥测数据看看哪些链接真的使用频繁。但总体上我对于调整各项目的位置比较保守，因为担心经常改变图标位置的话，会破坏用户养成的肌肉记忆。正是因为这个原因，增加“每日打卡”时，我决定新开一个组，而不是放进“常用网址”中。网络教学平台也只是最近格外常用，感觉放在“新冠疫情”中就还好。

自助打印复印确实很常用，不应该放在“其他”类，但和“成绩单打印”图标相同，文字又相似，直接这么换太容易让大家点错了吧（捂脸）不知道怎么操作比较好
