### ISSUE TITLE
这次UI图标更新有点阴间啊

### ISSUE THREAD

**Issue by TheLitFire** [ustclug/ustclife#46]
有一种国家缅怀日那种黑白色调的感觉（

**Comment by SmartHypercube** [comment]
related PR: #44 

我觉得还好吧，旧版图标也都是灰色的，或许可以考虑把现在的两种颜色再拉近一些？也欢迎提议新的配色方案。

因为不明确具体可以做的改进，先关闭 issue。

**Comment by TheLitFire** [comment]
原版虽然图标比较灰，但原灰色较重；老版本的栏目字体和一些条框也都有清晰的蓝色；特别是貌似左上角“USTC导航”字样的颜色也变了？
其实可以尝试把图标的基本灰度和某种蓝或者别的色混合一下什么的
