### ISSUE TITLE
更新自助打印服务网址

### ISSUE THREAD

**Issue by RubyOcelot** [ustclug/ustclife#47]
图书馆的打印服务已更换，参见 [图书馆自助文印服务使用说明](http://lib.ustc.edu.cn/%E6%9C%8D%E5%8A%A1%E6%8C%87%E5%8D%97/%E8%87%AA%E5%8A%A9%E6%96%87%E5%8D%B0%E6%9C%8D%E5%8A%A1%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/)

网址可以换成 http://weixinprinthost.woquyun.com/wq-web

**Comment by SmartHypercube** [comment]
HTTPS 好像可用，我先换成 https://weixinprinthost.woquyun.com/wq-web

edit：这个网址被重定向到 https://weixinprinthost.woquyun.com/wq-web/ ，故采用这个
