### ISSUE TITLE
校医院网址

### ISSUE THREAD

**Issue by CharlesLiu7** [ustclug/ustclife#5]
能否添加校医院的网址链接~？

**Comment by ghost** [comment]
等我假期处理一下
备忘：校医院 hospital.
超算中心 scc.

**Comment by ghost** [comment]
@doodlewind 请看最近的提交，我试图添加上server和hospital-o这两个图标，但是失败了。求指导正确使用fontawesome的姿势……

**Comment by doodlewind** [comment]
@ghost 试试这个 https://icomoon.io
