### ISSUE TITLE
可否加上健康打卡的网站？

### ISSUE THREAD

**Issue by GeraintLiu** [ustclug/ustclife#66]
最近学校好像要求每天都有要健康打卡了，可否把打卡网站:

- https://weixine.ustc.edu.cn/2020/login/
添加到主页上？谢谢！

**Comment by GeraintLiu** [comment]
抱歉，刚才没有发现，这个网站已经被添加到主页了

**Comment by SmartHypercube** [comment]
健康打卡网站现在确实不太容易找到，感谢你提醒。可惜我看了一下点击统计，“健康打卡”的点击量还不够加入“最多点击”，甚至不如同在一个区域的“正版软件”，我也不太明白是怎么回事，暂且关闭本 issue。
