### ISSUE TITLE
Remove baidu tracker

### ISSUE THREAD

**Issue by ononoki1** [ustclug/ustclife#68]
This site uses baidu's tracker, which is bad for users' (USTC students') privacy. Would you please remove it?

**Comment by SmartHypercube** [comment]
Currently, Baidu Analytics is used to count how many times each link is clicked, which is used to arrange all links on the page and ensure the best user experience. Please feel free to propose alternative solutions in the original issue: https://github.com/SmartHypercube/ustclife/issues/25 .
