### ISSUE TITLE
推广下开源插件-自动填写统一身份验证码-主要方便非校园网环境

### ISSUE THREAD

**Issue by cyh-ustc** [ustclug/ustclife#76]
https://microsoftedge.microsoft.com/addons/detail/ustcpass/hbdkmpdpjgdimjopgeklhhejedmpiioj
![db90d448ee4398e876f1c0e4fd272994-v1600](https://user-images.githubusercontent.com/18330024/209470300-1a8d7dc3-f725-45c3-a1d1-fb0ba5cd31f3.jpg)

**Comment by SmartHypercube** [comment]
浏览器插件安装链接不属于常用网址，不适合收录进本项目。这里可能更合适： https://github.com/zzh1996/USTC-Network-Resources
