### ISSUE TITLE
增加新版研究生教育教学管理系统

### ISSUE THREAD

**Issue by Adven00** [ustclug/ustclife#79]
详见通知https://gradschool.ustc.edu.cn/article/2845

**Comment by SmartHypercube** [comment]
考虑到旧系统仍然有一些用处，并且目前的链接会打开一个可以选择新旧两个系统的页面，暂时不改吧，等旧系统没用了，或者这个页面不工作了，再改。

另：看起来新系统里面说自己叫“研究生综合服务平台”，比起通知中用的叫法，我略倾向于用链接点开后自己显示的名字来命名链接。

**Comment by Zch106** [comment]
现在yjs.ustc.edu.cn已经404，新系统网址yjs1.ustc.edu.cn可以使用
